name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build Dockerfiles/notebook --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/dianhsu/notebook:latest
    
    - name: Login Aliyun Docker Hub
      run: echo "${{ secrets.ALIYUN_DOCKER_HUB_PASS }}" | docker login -u ${{ secrets.ALIYUN_DOCKER_HUB_USER }} --password-stdin
    
    - name: Push to Aliyun Docker Hub
      run: docker push registry.cn-hangzhou.aliyuncs.com/dianhsu/notebook:latest
